use crate::compiler::Compiler;

/// ...
pub struct Backend<E> {
    /// ...
    pub compiler: Compiler,
    /// ...
    pub environ: E,
}

/// ...
pub trait Environ {
    /// ...
    fn action_one(&mut self, value: u32);
    /// ...
    fn action_two(&mut self, value: u32);
}

impl<E: Environ> Backend<E> {
    /// ...
    pub fn render(&mut self) {
        // ...
        self.environ.action_one(32);
        // ...
        self.environ.action_two(32);
    }
}
